### ISSUE TITLE
additional-info

### ISSUE THREAD

**Issue by SakshiShreya** [SakshiShreya/gantt-proj#47]
Add additional info like:
- [x] logo (optional)
- [x] Project Start Date
- [ ] Project Manager
- [x] Description (optional)

**Comment by SakshiShreya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chart Additional Info](https://trello.com/c/YRbamZ5B/44-chart-additional-info)

**Comment by rohanmittal149** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Api to create logo](https://trello.com/c/KeDY3bX9/51-api-to-create-logo)
